FROM ubuntu:18.04

COPY . /bluecoin
WORKDIR /bluecoin

#shared libraries and dependencies
RUN apt update
RUN apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
RUN apt-get install -y libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev

#build faithcoin source
RUN ./autogen.sh
RUN ./configure --disable-wallet
RUN make
RUN make install


#open service port
EXPOSE 9777 19777

CMD ["bluecoind", "--printtoconsole"]